
create table PAY_METHOD (
ID_PAY_METHOD int(15),
constraint primary key(PK_PAY_METHOD),
CASH double (5,2),
BANK_CARD INT (16)
);


create table CLIENT_ (
USER_ID VARCHAR(30),
constraint primary key(PK_CLIENT),
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
PASSWORD VARCHAR(30),   
EMAIL VARCHAR(30),
NACIONALILTY VARCHAR(30),
PHONE_NUMBER int(10)   
);


CREATE TABLE ADDRESS(
ADDRESS_ID int(20), 
constraint primary key(PK_ADDRESS),
STREET VARCHAR(30),
FLAT_NUMBER INT(30),
FLAT VARCHAR(10),
POSTAL_CODE INT(10)
);


CREATE TABLE PRODUCT (
ID_PRODUCT int(20), 
constraint primary key(PK_PRODUCT),
NAME VARCHAR(30),
INGREDIENTS VARCHAR(30),
PRICE DOUBLE(5,2)    
);


CREATE TABLE CATEGORY (
CATEGORY_ID int(20),
constraint primary key(PK_CATEGORY),
CATEGORY_NAME VARCHAR(20)
);


CREATE TABLE ORDERS(
PRODUCT_ORDER_ID int(20),
constraint primary key(PK_ORDERS),
PRICE DOUBLE(5,2),  
NOTES VARCHAR(100),   
PRODUCT VARCHAR(20),
ORDER_DATE DATE,   
PAY_METHOD_ID INT(15),
DIRECTION_ID INT(20)
);


CREATE TABLE ORDER_LINES (
ORDER_LINES_ID int(30),
constraint primary key(PK_ORDER_LINES),
ORDER_ID INT(20),
PRODUCT_ID INT(20),
QUANTITY int(20)
);






